# Generated by Django 6.0.2 on 2026-02-25 13:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipients', '0010_add_monthly_recipient_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('unit', models.CharField(default='шт.', max_length=50, verbose_name='Единица измерения')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена в рублях', max_digits=10, verbose_name='Цена за единицу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DigitalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR-код')),
                ('bio', models.TextField(blank=True, help_text='Краткая биография жителя', verbose_name='Биография')),
                ('hobbies', models.CharField(blank=True, max_length=500, verbose_name='Увлечения')),
                ('favorite_activities', models.TextField(blank=True, verbose_name='Любимые занятия')),
                ('special_needs', models.TextField(blank=True, verbose_name='Особые потребности')),
                ('dietary_restrictions', models.CharField(blank=True, max_length=500, verbose_name='Диетические ограничения')),
                ('emergency_contact', models.CharField(blank=True, max_length=200, verbose_name='Экстренный контакт')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон экстренного контакта')),
                ('medical_notes', models.TextField(blank=True, verbose_name='Медицинские заметки')),
                ('is_public', models.BooleanField(default=False, help_text='Доступен ли профиль для просмотра по QR-коду', verbose_name='Публичный профиль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_profile', to='recipients.recipient', verbose_name='Получатель услуг')),
            ],
            options={
                'verbose_name': 'Цифровой профиль',
                'verbose_name_plural': 'Цифровые профили',
            },
        ),
        migrations.CreateModel(
            name='MonthlyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Подана'), ('approved', 'Утверждена'), ('completed', 'Выполнена')], default='draft', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Общая стоимость заявки', max_digits=12, verbose_name='Общая сумма')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_food_requests', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_requests', to='recipients.recipient', verbose_name='Получатель услуг')),
            ],
            options={
                'verbose_name': 'Заявка на паёк',
                'verbose_name_plural': 'Заявки на паёк',
                'ordering': ['-year', '-month', 'recipient'],
                'unique_together': {('recipient', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена на момент добавления', max_digits=10, verbose_name='Цена за единицу')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_items', to='modules.product', verbose_name='Продукт')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='modules.monthlyrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Позиция заявки',
                'verbose_name_plural': 'Позиции заявок',
                'unique_together': {('request', 'product')},
            },
        ),
    ]
