# Generated by Django 6.0.2 on 2026-02-25 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        ('recipients', '0010_add_monthly_recipient_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PensionAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pension_type', models.CharField(blank=True, help_text='Например: страховая, социальная, по инвалидности', max_length=100, verbose_name='Тип пенсии')),
                ('pension_number', models.CharField(blank=True, max_length=50, verbose_name='Номер пенсионного дела')),
                ('monthly_pension_amount', models.DecimalField(decimal_places=2, default=0, help_text='Базовая ежемесячная сумма пенсии', max_digits=10, verbose_name='Ежемесячная сумма пенсии')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Накопленная сумма на счёте', max_digits=12, verbose_name='Текущий баланс')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pension_account', to='recipients.recipient', verbose_name='Получатель услуг')),
            ],
            options={
                'verbose_name': 'Пенсионный счёт',
                'verbose_name_plural': 'Пенсионные счета',
            },
        ),
        migrations.CreateModel(
            name='PensionExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма списания', max_digits=10, verbose_name='Сумма расхода')),
                ('category', models.CharField(choices=[('food', 'Продукты питания'), ('medicine', 'Лекарства'), ('clothing', 'Одежда'), ('hygiene', 'Средства гигиены'), ('services', 'Услуги'), ('request', 'Исполнение заявки'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('expense_date', models.DateField(blank=True, null=True, verbose_name='Дата расхода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='modules.pensionaccount', verbose_name='Пенсионный счёт')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('related_request', models.ForeignKey(blank=True, help_text='Заявка на паёк, если расход связан с ней', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pension_expenses', to='modules.monthlyrequest', verbose_name='Связанная заявка')),
            ],
            options={
                'verbose_name': 'Расход пенсии',
                'verbose_name_plural': 'Расходы пенсий',
                'ordering': ['-year', '-month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PensionAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма начисленной пенсии', max_digits=10, verbose_name='Сумма начисления')),
                ('accrued_date', models.DateField(blank=True, help_text='Дата фактического начисления', null=True, verbose_name='Дата начисления')),
                ('source', models.CharField(blank=True, help_text='Например: ПФР, СФР', max_length=100, verbose_name='Источник')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accruals', to='modules.pensionaccount', verbose_name='Пенсионный счёт')),
            ],
            options={
                'verbose_name': 'Начисление пенсии',
                'verbose_name_plural': 'Начисления пенсий',
                'ordering': ['-year', '-month'],
                'unique_together': {('account', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PensionSavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Отложенная сумма', max_digits=10, verbose_name='Сумма накопления')),
                ('purpose', models.CharField(blank=True, help_text='На что копятся средства', max_length=200, verbose_name='Цель накопления')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='modules.pensionaccount', verbose_name='Пенсионный счёт')),
            ],
            options={
                'verbose_name': 'Накопление пенсии',
                'verbose_name_plural': 'Накопления пенсий',
                'ordering': ['-year', '-month'],
                'unique_together': {('account', 'year', 'month')},
            },
        ),
    ]
