# Generated by Django 6.0.2 on 2026-02-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('residential', 'Проживания'), ('mercy', 'Милосердие'), ('hospital', 'Больница'), ('vacation', 'Отпуск'), ('deceased', 'Умер')], default='residential', help_text='Определяет статус проживающего', max_length=20, verbose_name='Тип отделения'),
        ),
    ]
