# Generated by Django 6.0.2 on 2026-02-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department_department_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Максимальное количество проживающих', verbose_name='Количество мест'),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
