# Generated by Django 5.2.11 on 2026-03-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_department_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='is_mercy',
        ),
    ]
