# Generated by Django 5.2.11 on 2026-03-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_is_mercy_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('residential', 'Проживания'), ('mercy', 'Милосердие')], default='residential', help_text='Определяет статус проживающего', max_length=20, verbose_name='Тип отделения'),
        ),
    ]
