# Generated by Django 5.2.11 on 2026-03-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_update_department_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_active_status', models.BooleanField(default=True, help_text='Активен ли проживающий в этом статусе', verbose_name='Активный статус')),
                ('requires_department', models.BooleanField(default=True, help_text='Нужно ли выбирать отделение для этого типа размещения', verbose_name='Требует отделения')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип местоположения',
                'verbose_name_plural': 'Типы местоположения',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('residential', 'Проживания'), ('mercy', 'Милосердие')], default='residential', help_text='Тип отделения', max_length=20, verbose_name='Тип отделения'),
        ),
    ]
