# Generated by Django 5.2.11 on 2026-03-07 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_organization_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(blank=True, max_length=15, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_organizations', to='core.employee', verbose_name='Руководитель'),
        ),
    ]
