# Generated by Django 5.2.11 on 2026-03-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_organization_ogrn_alter_organization_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес регистрации'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_department_code',
            field=models.CharField(blank=True, max_length=7, verbose_name='Код подразделения'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_issued_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кем выдан паспорт'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, max_length=6, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_series',
            field=models.CharField(blank=True, max_length=4, verbose_name='Серия паспорта'),
        ),
    ]
