# Generated by Django 5.2.11 on 2026-03-07 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_employee_address_employee_passport_department_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_settings', to='core.organization', verbose_name='Организация-заказчик')),
                ('customer_signatory', models.ForeignKey(blank=True, help_text='Сотрудник, подписывающий акты от имени заказчика', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_signatory_settings', to='core.employee', verbose_name='Подписант от заказчика')),
                ('executor_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor_settings', to='core.organization', verbose_name='Организация-исполнитель')),
                ('executor_signatory', models.ForeignKey(blank=True, help_text='Сотрудник, подписывающий акты от имени исполнителя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor_signatory_settings', to='core.employee', verbose_name='Подписант от исполнителя')),
            ],
            options={
                'verbose_name': 'Настройки системы',
                'verbose_name_plural': 'Настройки системы',
            },
        ),
    ]
