# Generated by Django 6.0.2 on 2026-02-13 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер договора')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действует')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'ИППСУ (Договор)',
                'verbose_name_plural': 'ИППСУ (Договоры)',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('room', models.CharField(blank=True, max_length=20, verbose_name='Комната')),
                ('status', models.CharField(choices=[('active', 'Проживает'), ('vacation', 'Отпуск'), ('hospital', 'Больница'), ('discharged', 'Выбыл')], default='active', max_length=20, verbose_name='Статус')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='Дата заселения')),
                ('discharge_date', models.DateField(blank=True, null=True, verbose_name='Дата выбытия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Получатель социальных услуг',
                'verbose_name_plural': 'Получатели социальных услуг',
                'ordering': ['last_name', 'first_name', 'patronymic'],
            },
        ),
        migrations.CreateModel(
            name='ContractService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='recipients.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Услуга в ИППСУ',
                'verbose_name_plural': 'Услуги в ИППСУ',
            },
        ),
    ]
