# Generated by Django 6.0.2 on 2026-02-13 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('recipients', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_services', to='services.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to='core.department', verbose_name='Отделение'),
        ),
        migrations.AddField(
            model_name='contract',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='recipients.recipient', verbose_name='Получатель услуг'),
        ),
        migrations.AlterUniqueTogether(
            name='contractservice',
            unique_together={('contract', 'service')},
        ),
    ]
