# Generated by Django 6.0.2 on 2026-02-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractservice',
            name='max_quantity_per_month',
            field=models.PositiveIntegerField(blank=True, help_text='Ограничение на количество оказаний услуги в месяц. Оставьте пустым для снятия ограничения.', null=True, verbose_name='Макс. кол-во в месяц'),
        ),
    ]
