# Generated by Django 6.0.2 on 2026-02-14 19:52

import apps.recipients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0003_contractservice_max_quantity_per_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='photo',
            field=models.ImageField(blank=True, help_text='Фотография получателя услуг', null=True, upload_to=apps.recipients.models.recipient_photo_path, verbose_name='Фотография'),
        ),
    ]
