# Generated by Django 6.0.2 on 2026-02-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0004_add_photo_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractservice',
            name='max_quantity_per_month',
        ),
    ]
