# Generated by Django 6.0.2 on 2026-02-21 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department_department_type'),
        ('recipients', '0005_remove_contractservice_max_quantity_per_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='status',
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('active', 'Проживает'), ('vacation', 'Отпуск'), ('hospital', 'Больница'), ('discharged', 'Выбыл')], max_length=20, null=True, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(choices=[('active', 'Проживает'), ('vacation', 'Отпуск'), ('hospital', 'Больница'), ('discharged', 'Выбыл')], max_length=20, verbose_name='Новый статус')),
                ('reason', models.TextField(blank=True, verbose_name='Причина/Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('new_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivals', to='core.department', verbose_name='Новое отделение')),
                ('old_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departures', to='core.department', verbose_name='Предыдущее отделение')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='recipients.recipient', verbose_name='Получатель услуг')),
            ],
            options={
                'verbose_name': 'История статуса',
                'verbose_name_plural': 'История статусов',
                'ordering': ['-created_at'],
            },
        ),
    ]
