# Generated by Django 6.0.2 on 2026-02-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0007_alter_recipient_discharge_date_placementhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Среднедушевой доход получателя социальных услуг', max_digits=10, verbose_name='Среднедушевой доход'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='pension_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Фактически перечислено Пенсионным фондом в ДСО', max_digits=10, verbose_name='Перечислено ПФ'),
        ),
    ]
