# Generated by Django 6.0.2 on 2026-02-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0008_add_income_pension_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Среднедушевой доход получателя социальных услуг', max_digits=10, null=True, verbose_name='Среднедушевой доход'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='pension_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Фактически перечислено Пенсионным фондом в ДСО', max_digits=10, null=True, verbose_name='Перечислено ПФ'),
        ),
    ]
