# Generated by Django 6.0.2 on 2026-02-23 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0009_change_income_pension_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRecipientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('income', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Среднедушевой доход получателя социальных услуг', max_digits=10, null=True, verbose_name='Среднедушевой доход')),
                ('pension_payment', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Фактически перечислено Пенсионным фондом в ДСО', max_digits=10, null=True, verbose_name='Перечислено ПФ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_data', to='recipients.recipient', verbose_name='Получатель услуг')),
            ],
            options={
                'verbose_name': 'Данные проживающего по месяцам',
                'verbose_name_plural': 'Данные проживающих по месяцам',
                'ordering': ['-year', '-month', 'recipient'],
                'unique_together': {('recipient', 'year', 'month')},
            },
        ),
    ]
