# Generated by Django 5.2.11 on 2026-02-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0011_merge_history_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyrecipientdata',
            options={'ordering': ['-year', '-month', 'recipient'], 'verbose_name': 'Финансовые записи в акте', 'verbose_name_plural': 'Финансовые записи в акте'},
        ),
    ]
