# Generated by Django 5.2.11 on 2026-02-28 19:52

import django.db.models.deletion
from django.db import migrations, models


def populate_placement_from_department(apps, schema_editor):
    """
    Заполняет поле placement на основе текущего отделения.
    Логика:
    - Если отделение имеет department_type в ['residential', 'mercy'] -> 'internat'
    - Если department_type == 'vacation' -> 'vacation'
    - Если department_type == 'hospital' -> 'hospital'
    - Если department_type == 'deceased' -> 'discharged'
    - Если нет отделения -> 'internat' (по умолчанию)
    """
    Recipient = apps.get_model('recipients', 'Recipient')
    Department = apps.get_model('core', 'Department')
    
    # Маппинг типов отделений на размещение
    dept_to_placement = {
        'residential': 'internat',
        'mercy': 'internat',
        'vacation': 'vacation',
        'hospital': 'hospital',
        'deceased': 'discharged',
    }
    
    for recipient in Recipient.objects.all():
        if recipient.department:
            dept_type = recipient.department.department_type
            recipient.placement = dept_to_placement.get(dept_type, 'internat')
        else:
            recipient.placement = 'internat'
    
    Recipient.objects.bulk_update(
        [r for r in Recipient.objects.all()],
        ['placement']
    )


def populate_history_placements(apps, schema_editor):
    """
    Заполняет поля old_placement и new_placement в истории на основе старых полей.
    """
    RecipientHistory = apps.get_model('recipients', 'RecipientHistory')
    Department = apps.get_model('core', 'Department')
    
    # Маппинг типов отделений на размещение
    dept_to_placement = {
        'residential': 'internat',
        'mercy': 'internat',
        'vacation': 'vacation',
        'hospital': 'hospital',
        'deceased': 'discharged',
    }
    
    for history in RecipientHistory.objects.all():
        # Заполняем new_placement из new_status или new_department
        if history.new_status:
            # Маппинг старых статусов на новые размещения
            status_to_placement = {
                'active': 'internat',
                'vacation': 'vacation',
                'hospital': 'hospital',
                'discharged': 'discharged',
            }
            history.new_placement = status_to_placement.get(history.new_status, 'internat')
        elif history.new_department:
            dept_type = history.new_department.department_type
            history.new_placement = dept_to_placement.get(dept_type, 'internat')
        
        # Заполняем old_placement из old_status или old_department
        if history.old_status:
            status_to_placement = {
                'active': 'internat',
                'vacation': 'vacation',
                'hospital': 'hospital',
                'discharged': 'discharged',
            }
            history.old_placement = status_to_placement.get(history.old_status, 'internat')
        elif history.old_department:
            dept_type = history.old_department.department_type
            history.old_placement = dept_to_placement.get(dept_type, 'internat')
    
    RecipientHistory.objects.bulk_update(
        [h for h in RecipientHistory.objects.all()],
        ['old_placement', 'new_placement']
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_department_capacity'),
        ('recipients', '0012_merge_history_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='placement',
            field=models.CharField(choices=[('internat', 'Интернат'), ('vacation', 'Отпуск'), ('hospital', 'Больница'), ('discharged', 'Выбыл')], default='internat', help_text='Текущее место нахождения проживающего', max_length=20, verbose_name='Размещение'),
        ),
        migrations.AddField(
            model_name='recipienthistory',
            name='new_placement',
            field=models.CharField(blank=True, choices=[('internat', 'Интернат'), ('vacation', 'Отпуск'), ('hospital', 'Больница'), ('discharged', 'Выбыл')], max_length=20, null=True, verbose_name='Новое размещение'),
        ),
        migrations.AddField(
            model_name='recipienthistory',
            name='old_placement',
            field=models.CharField(blank=True, choices=[('internat', 'Интернат'), ('vacation', 'Отпуск'), ('hospital', 'Больница'), ('discharged', 'Выбыл')], max_length=20, null=True, verbose_name='Предыдущее размещение'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to='core.department', verbose_name='Отделение'),
        ),
        migrations.AlterField(
            model_name='recipienthistory',
            name='new_status',
            field=models.CharField(blank=True, choices=[('internat', 'Интернат'), ('vacation', 'Отпуск'), ('hospital', 'Больница'), ('discharged', 'Выбыл')], max_length=20, null=True, verbose_name='Новый статус (устарело)'),
        ),
        migrations.AlterField(
            model_name='recipienthistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('internat', 'Интернат'), ('vacation', 'Отпуск'), ('hospital', 'Больница'), ('discharged', 'Выбыл')], max_length=20, null=True, verbose_name='Предыдущий статус (устарело)'),
        ),
        # Миграция данных
        migrations.RunPython(populate_placement_from_department, migrations.RunPython.noop),
        migrations.RunPython(populate_history_placements, migrations.RunPython.noop),
    ]
