# Generated by Django 5.2.11 on 2026-03-05 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_location_type_data'),
        ('recipients', '0013_add_placement_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='location_type',
            field=models.ForeignKey(blank=True, help_text='Текущее местоположение проживающего', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='core.locationtype', verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='placement',
            field=models.CharField(choices=[('internat', 'Интернат'), ('vacation', 'Отпуск'), ('hospital', 'Больница'), ('discharged', 'Выбыл')], default='internat', help_text='Используйте location_type', max_length=20, verbose_name='Размещение (устарело)'),
        ),
    ]
