# Generated by Django 5.2.11 on 2026-03-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0015_migrate_placement_to_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='passport_department_code',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Код подразделения'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='passport_issued_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='passport_number',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='passport_series',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Серия паспорта'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон'),
        ),
    ]
