# Generated by Django 6.0.2 on 2026-02-13 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код услуги')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование услуги')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена (руб.)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_services', to='services.service', verbose_name='Родительская услуга')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['code', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата оказания')),
                ('quantity', models.DecimalField(decimal_places=0, default=1, max_digits=5, verbose_name='Количество')),
                ('price_at_service', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена на момент оказания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_services', to=settings.AUTH_USER_MODEL, verbose_name='Кто оказал услугу')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='recipients.recipient', verbose_name='Получатель услуги')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Запись табеля',
                'verbose_name_plural': 'Записи табеля',
                'ordering': ['-date', 'recipient', 'service'],
                'unique_together': {('recipient', 'service', 'date')},
            },
        ),
    ]
