# Generated by Django 6.0.2 on 2026-02-21 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: "ежедневно", "1 в месяц"', max_length=100, verbose_name='Название')),
                ('short_name', models.CharField(help_text='Для отображения в таблицах', max_length=30, verbose_name='Краткое название')),
                ('period_type', models.CharField(choices=[('day', 'В день'), ('week', 'В неделю'), ('month', 'В месяц'), ('year', 'В год')], default='month', help_text='Период, за который считается количество оказаний', max_length=10, verbose_name='Тип периода')),
                ('times_per_period', models.PositiveIntegerField(blank=True, help_text='Количество раз за указанный период. Оставьте пустым для снятия ограничения.', null=True, verbose_name='Раз за период')),
                ('is_approximate', models.BooleanField(default=False, help_text='Отмечает нормативы типа "до N раз" (жёлтый цвет в интерфейсе)', verbose_name='Приблизительный норматив')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Периодичность услуги',
                'verbose_name_plural': 'Периодичности услуг',
                'ordering': ['order', 'period_type', 'times_per_period'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='max_quantity_per_month',
            field=models.PositiveIntegerField(blank=True, help_text='Ограничение на количество оказаний услуги в месяц. Заполняется автоматически из периодичности или вручную.', null=True, verbose_name='Макс. кол-во в месяц'),
        ),
        migrations.AddField(
            model_name='service',
            name='frequency',
            field=models.ForeignKey(blank=True, help_text='Норматив оказания услуги. Определяет лимит в месяц.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicefrequency', verbose_name='Периодичность (норматив)'),
        ),
    ]
