# Generated by Django 6.0.2 on 2026-02-22 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department_department_type'),
        ('services', '0003_add_frequency_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], help_text='День недели, в который оказывается услуга', verbose_name='День недели')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Количество оказаний услуги в этот день', verbose_name='Количество')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_schedules', to='core.department', verbose_name='Отделение')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Расписание услуги',
                'verbose_name_plural': 'Расписания услуг',
                'ordering': ['department', 'day_of_week', 'service'],
                'unique_together': {('service', 'department', 'day_of_week')},
            },
        ),
    ]
