# Generated by Django 6.0.2 on 2026-02-23 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0010_add_monthly_recipient_data'),
        ('services', '0004_add_service_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('is_locked', models.BooleanField(default=True, verbose_name='Заблокировано')),
                ('locked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата блокировки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabel_locks', to=settings.AUTH_USER_MODEL, verbose_name='Заблокировал')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabel_locks', to='recipients.recipient', verbose_name='Получатель услуги')),
            ],
            options={
                'verbose_name': 'Блокировка табеля',
                'verbose_name_plural': 'Блокировки табеля',
                'ordering': ['-year', '-month', 'recipient'],
                'unique_together': {('recipient', 'year', 'month')},
            },
        ),
    ]
