# Generated by Django 5.2.11 on 2026-02-28 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0010_add_monthly_recipient_data'),
        ('services', '0005_add_tabel_lock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('biweekly', 'Раз в 2 недели'), ('monthly', 'Ежемесячно'), ('quarterly', 'Ежеквартально'), ('custom', 'По индивидуальному графику')], default='monthly', help_text='Как часто получатель должен получать данную услугу', max_length=20, verbose_name='Периодичность получения')),
                ('custom_frequency', models.CharField(blank=True, help_text='Описание индивидуального графика (например: "по понедельникам и четвергам")', max_length=100, verbose_name='Индивидуальный график')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о назначении услуги', verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, help_text='Отключите, если получатель временно не получает услугу', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_recipients', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_services', to='recipients.recipient', verbose_name='Получатель услуги')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_recipients', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Назначение услуги',
                'verbose_name_plural': 'Назначения услуг',
                'ordering': ['service__code', 'recipient__last_name'],
                'unique_together': {('service', 'recipient')},
            },
        ),
    ]
