# Generated by Django 5.2.11 on 2026-03-03 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_add_service_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerecipient',
            name='custom_frequency',
        ),
        migrations.RemoveField(
            model_name='servicerecipient',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='servicerecipient',
            name='notes',
        ),
    ]
