# Generated by Django 5.2.11 on 2026-03-08 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0016_add_recipient_passport_fields'),
        ('services', '0007_remove_service_recipient_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecipientLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('is_locked', models.BooleanField(default=True, verbose_name='Заблокировано')),
                ('locked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата блокировки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_recipient_locks', to=settings.AUTH_USER_MODEL, verbose_name='Заблокировал')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_locks', to='recipients.recipient', verbose_name='Получатель услуги')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_locks', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Блокировка услуги получателя',
                'verbose_name_plural': 'Блокировки услуг получателей',
                'ordering': ['-year', '-month', 'service', 'recipient'],
                'unique_together': {('service', 'recipient', 'year', 'month')},
            },
        ),
    ]
